---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: exposed-nginx-preprovisioned-lb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exposed-nginx-preprovisioned-lb
  template:
    metadata:
      labels:
        app: exposed-nginx-preprovisioned-lb
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - name: http
          containerPort: 80
        volumeMounts:
        - name: lb
          mountPath: /usr/share/nginx/html/lb
  volumeClaimTemplates:
  - metadata:
      name: lb
      annotations:
        lb.stackable.tech/lb-name: exposed-nginx-preprovisioned-lb
    spec:
      accessModes:
      - ReadWriteMany
      storageClassName: lb.stackable.tech
      resources:
        requests:
          storage: 1
---
apiVersion: lb.stackable.tech/v1alpha1
kind: LoadBalancer
metadata:
  name: exposed-nginx-preprovisioned-lb
spec:
  className: lb-external
  ports:
  - name: http
    port: 9998
